### ISSUE TITLE
FILE_LIBRARY_CASCADE_DELETE / MEIDA_LIBRARY_CASCADE_DELETE doesn't delete successful

### ISSUE THREAD

**Issue by EPInformatyka** [area17/twill#768] opened 2020-11-23 01:10 UTC
if set variables FILE_LIBRARY_CASCADE_DELETE or MEDIA_LIBRARY_CASCADE_DELETE=true, the empty directory doesn't delete from server

**Comment by ifox** [comment] 2021-06-30 10:45
Duplicate of #375 which we are going to fix. Thanks for reporting.

**Closed by ifox** 2021-06-30 10:45 UTC
