### ISSUE TITLE
[3.x] Module preview and revision preview are not previewing the correct content

### ISSUE THREAD

**Issue by silviaho** [area17/twill#2015] opened 2022-12-21 08:35 UTC
## Description

The preview function is not delivering the correct block editor content for the below scenarios:

- Scenario 1 (Module preview): Cannot preview the edited block editor content without saving
- Scenario 2 (Revision preview):  Cannot preview the block editor content of a selected revision without restoring

Instead, the currently published version of the block editor content is shown in both scenarios.

### Steps to reproduce

1. Save and publish the block editor content: 
![image](https://user-images.githubusercontent.com/77000006/208851820-be6d6203-e89d-4a35-ae27-a55d8b6f4e60.png)

2. 
For scenario 1, edit the block editor content and click "Preview changes" (without saving the content)
![image](https://user-images.githubusercontent.com/77000006/208854007-887d5eed-6c85-4776-95d3-fd3a1fc11d34.png)

For scenario 2, select a revision version
![image](https://user-images.githubusercontent.com/77000006/208856992-b25ccb1f-8521-4f1b-87fd-01bfe84ce5d7.png)

### Expected result

For scenario 1, should be able to preview the unsaved edited content
![image](https://user-images.githubusercontent.com/77000006/208854691-b97caf03-560b-4337-b67c-a22c97089630.png)

For scenario 2, should be able to preview the revision content
![image](https://user-images.githubusercontent.com/77000006/208854830-fd7d409c-e8c5-4882-8486-5be1e662c2aa.png)

### Actual result
The published version of the block editor content is shown instead for both scenarios.
For scenario 1
![image](https://user-images.githubusercontent.com/77000006/208855166-b7bdf7de-af53-47fe-b02c-795da2830cba.png)
For scenario 2
![image](https://user-images.githubusercontent.com/77000006/208855213-12329903-72c5-4b1a-acfb-268c2c04ca3c.png)

### Versions

Twill 3.0.0-rc1

Laravel Framework 9.40.1

PHP 8.1.9

MySQL 8.0

**Comment by ifox** [comment] 2022-12-21 10:12
Hi @silviaho thanks for reporting this.

It seems like you forgot to mention that you are using `enableDraftRevisions` on this module, which might be the problem. Is the preview correctly showing the unsaved content when you are editing the latest revision?

**Comment by silviaho** [comment] 2022-12-21 11:15
> Hi @silviaho thanks for reporting this.
> 
> It seems like you forgot to mention that you are using `enableDraftRevisions` on this module, which might be the problem. Is the preview correctly showing the unsaved content when you are editing the latest revision?

Hi @ifox, thanks for your quick reply. I did use `enableDraftRevisions` on this module and the preview could not show the unsaved content when I am editing the latest revision.
Also, I retried the above cases disabling the `enableDraftRevisions` feature, but the issue remains.

**Comment by ifox** [comment] 2022-12-21 11:22
@silviaho if the issue remains, since I'm not able to reproduce it with a standard setup, I need to ask you about how you are rendering your blocks. Are you using `renderBlocks()`?

**Comment by silviaho** [comment] 2022-12-21 11:45
> @silviaho if the issue remains, since I'm not able to reproduce it with a standard setup, I need to ask you about how you are rendering your blocks. Are you using `renderBlocks()`?

Yes we are using `renderBlocks()`
![image](https://user-images.githubusercontent.com/77000006/208894599-52d5f232-182e-41f3-b987-847cf2d4b47f.png)

The issue only happens to block editor content. The preview feature works fine for other fields. Could you please try reproducing the issue using block editor? Thanks!

**Comment by ifox** [comment] 2022-12-21 11:58
Thanks. How are you accessing blocks values inside of your blocks?

**Comment by silviaho** [comment] 2022-12-22 03:55
> Thanks. How are you accessing blocks values inside of your blocks?

I access the block values with `$block->translatedInput('html')` in the above examples
![image](https://user-images.githubusercontent.com/77000006/209038131-e9f73643-cf8c-4083-ae7c-ecda602b3f62.png)

Apart from the custom TinyMCE HTML editor used above, I also tried simple input fields, but the preview problem remains.
![image](https://user-images.githubusercontent.com/77000006/209051660-aa20e534-354b-4079-aa79-7fc9e34ee8e1.png)

**Comment by ifox** [comment] 2022-12-22 11:16
Thank you. I'm able to reproduce from a clean RC1 install and this seems like a very recent regression as we have projects running on the beta releases that do not have this issue. We're going to investigate and address asap. cc @haringsrob

**Comment by ifox** [comment] 2022-12-22 11:21
Interestingly I'm able to reproduce on beta2 as well.

**Comment by silviaho** [comment] 2022-12-23 02:13
@ifox Thanks and looking forward to your findings!

**Comment by haringsrob** [comment] 2023-01-09 12:25
This is resolved, will be in the next rc.

**Closed by haringsrob** 2023-01-09 12:25 UTC
