### ISSUE TITLE
Empty related browser field in blocks breaks admin UI

### ISSUE THREAD

**Issue by daun** [area17/twill#1404] opened 2022-01-26 12:30 UTC
## Description

Related browser fields in blocks break when they are empty, causing an exception: `Repository class not found for model 'Related'`.

### Steps to reproduce

- Add related browser field to block

```blade
    @formField('browser', [
        'endpoints' => $linkEndpoints,
        'name' => 'related',
        'label' => 'Page',
    ])
```

- Leave browser field empty
- Save page in admin
- Reload edit screen in admin

### Expected result

Empty browser fields should be handled gracefully.

### Actual result

Exception is thrown: `Repository class not found for model 'Related'`.

### Versions

Twill version:  2.6.0
Laravel version: 8.69
PHP version: 8.0.8
Database engine: MySQL

**Comment by haringsrob** [comment] 2022-01-28 08:07
Hello @daun,

I am trying to reproduce this issue.

So I have added a browser field to a block:

```
@formField('browser', [
    'endpoints' => [
        [
          'label' => 'Categories',
          'value' => '/categories/browser',
        ],
    ],
    'name' => 'categories',
    'label' => 'Categories',
    'max' => 1,
])
```

Then create a new page, add a block and save.

Then refresh the page but all seems to load fine.

Am I missing something?

**Comment by daun** [comment] 2022-01-28 11:16
@haringsrob It only occurs for browsers that save in the `related` table and whose field name doesn't match an existing model. If you rename the browser field `related` or `references` or similar, it should fail.

**Comment by haringsrob** [comment] 2022-02-02 08:04
Hey @daun, the example above does save in the related table.

I do not understand what you mean exactly. Could you set up a minimum install with a reproducible example?

**Comment by daun** [comment] 2022-02-02 13:51
@haringsrob If you rename the form field from `categories` to `related` (or even `lorem_ipsum`), does it still not reproduce? It only fails for me if the form field name does **not** match an existing model name.

**Comment by ifox** [comment] 2022-02-11 12:30
Hi @daun, we investigated this further. The only way for this code path to happen would be that you have stale/legacy data in your block's `content.browsers` array in the JSON in database. That's the only way the code can get to that check on the related table.

**Comment by ifox** [comment] 2022-02-11 12:31
Don't get me wrong your PR makes sense and needs to be merged in any case, but I don't think it is addressing the root cause of how you ended up in that situation.

**Comment by ifox** [comment] 2022-02-11 12:40
See https://github.com/area17/twill/pull/1405/files#diff-2169a5bad4e41f78f2184f503295f4cfb5cdd1da345622241cd389b36da5f9bbR286

**Comment by daun** [comment] 2022-02-11 13:04
@ifox Appreciate you looking into it!

I'm still convinced there's a twist in the logic — the default path requires the related items to not be empty. That means an empty array in the JSON data would be enough to trigger the other code path, regardless of browser name or endpoint. No need for it to be stale.

The check for the happy path is:
```php
Schema::hasTable(config('twill.related_table', 'twill_related'))
    && $block->getRelated($relation)->isNotEmpty()
```

So it executes if

- the related table exists (AND)
- the related items for this browser are not empty (i.e. at least one item)

Switching that around means the other code path is executed if either 

- the related table does not exist (OR)
- the related items are empty (not defined or count of zero)

I don't think the second code path should execute if the browser field is defined but there's zero items in it. But that's there the backward compatibility comes in, I guess.

Hope I'm not embarrassing myself here by overlooking something obvious.

**Comment by ifox** [comment] 2022-02-11 13:10
No worries about being embarrassed, we're all in the same boat 🙂

You're totally right, but consider the line above that code:
```php
return Collection::make($block['content']['browsers'])->mapWithKeys(function ($ids, $relation) use ($block) {
```

If the collection is empty, there is nothing to map so the code should not get to the line we're discussing.

**Comment by daun** [comment] 2022-02-11 13:20
@ifox That collection is a collection of browser fields, isn't it? Wouldn't it then still loop over all the browser fields even in the case of an empty browser field?

E.g., a block with a single browser field called `references` with no items attached should produce the following JSON data. That would then loop over `browsers`, but `references` is empty. Or does Twill remove the `references` key on save because it's an empty array?

```json
{
  "browsers": {
    "references": []
  }
}
```

**Comment by ifox** [comment] 2022-02-11 16:55
I will dig deeper into this again, but to follow up quickly, I believe the frontend wouldn't send the browser key if it's empty, but that's probably what's going on.

**Comment by daun** [comment] 2022-02-11 20:22
@ifox You're right, it seems like it strips out empty browsers. Could it be related to nested browsers in repeaters? I have a vague feeling it has to do with that. Let me assemble a good test case before wasting more of your time.

**Closed** 2022-03-02 10:24 UTC
Labels: type: bug
