### ISSUE TITLE
date_picker not saving date

### ISSUE THREAD

**Issue by iliabaan** [area17/twill#2237] opened 2023-04-17 12:28 UTC
## Description

There is a bug in the date_picker field of the model which is preventing the user from saving date.

### Steps to reproduce

Open the application and navigate to the date_picker field.
Click on the date_picker field to open the date picker.
Select a date from the date picker.
Click on the "Save" button to save the data.

### Expected result

The selected date should be saved successfully and the user should receive a confirmation message.

### Actual result

After selecting a date and clicking on the "Save" button, nothing happens. The selected date is not saved and confirmation message is displayed.

### Versions

Twill version: 3.0.1
Laravel version: 10.7.1
PHP version: 8.1
Database engine:  MySQL 5.7

**Comment by ifox** [comment] 2023-04-17 12:31
Hi @iliabaan, did you add your date field to your model fillables, and did you set a datetime cast for it?

**Comment by iliabaan** [comment] 2023-04-17 14:10
Hello! Yep, I did it. 

`protected $fillable = [
        'published',
        'title',
        'description',
        'content',
        'publish_date',
        'sources',
        'sector_id'
    ];
    
protected $casts = [
        'sources' => 'array',
        'publish_date' => 'datetime',
    ];`

**Comment by dweerd** [comment] 2023-06-16 09:06
@ifox I have the same issue. Worked before upgrade to Twill 3. Looking in the browser console, I see the value sent to the server is `null` , so seems to be a frontend issue. Another thing that stands out: the first time I select a date, the datepicker input field stays empty.

**Comment by ifox** [comment] 2023-06-16 09:08
Hi @dweerd are you sure that you are using the latest compiled assets? `php artisan twill-update`

**Comment by dweerd** [comment] 2023-06-16 09:29
Yes! To be sure, I did it again, but made no difference.

**Comment by ifox** [comment] 2023-06-16 09:33
Is there a cast on that column in your model?

**Comment by dweerd** [comment] 2023-06-16 09:42
No, but I have added it now but makes no difference. As said, it seems to be wrong in the frontend:

![image](https://github.com/area17/twill/assets/4249354/fc040f4a-e59b-474d-a1c5-b1763dbe99c6)

whatever I select, it sends null from the frontend to the server.

**Comment by ifox** [comment] 2023-06-16 09:51
Please share the code you are using to declare that form field.

**Comment by dweerd** [comment] 2023-06-16 10:29
```
public function getForm(TwillModelContract $model): Form
{
	$form = parent::getForm($model);

	$form->add(
		Datepicker::make()
			->name('date')
			->label('Datum')
			->altFormat('j F Y')
			->withoutTime()
	);
}
```

**Comment by BezBIS** [comment] 2023-06-27 15:32
I am also experiencing the same issue. My code for adding the datepicker is similar to that of dweerd and the date field is set as a 'fillable'.
```
$form->add(
            DatePicker::make()->withoutTime(true)->name('date')->label('Date')
        );
```
```
 protected $fillable = [
        'published',
        'title',
        'description',
        'details',
        'location',
        'date'
    ];
```

**Comment by ismarxo** [comment] 2023-07-18 07:46
this behavior is achieved due to incorrect work with the `->withoutTime()` call

the problem is in the frontend component, if you select it a second time, the result is saved in the input

**Comment by thewush** [comment] 2023-07-21 17:33
> 

Don't suppose you have a fix for this? Client's not gonna want to click multiple times to set a date.

**Comment by BezBIS** [comment] 2023-08-16 09:06
> this behavior is achieved due to incorrect work with the `->withoutTime()` call
> 
> the problem is in the frontend component, if you select it a second time, the result is saved in the input

While clicking the date a 2nd time does fill the input most of the time for me, I have noticed that about 99% of the time it doesn't save the input's value to the database; thus rendering the input useless. Currently, I have to manually insert dates into the database. This is not a huge inconvenience, as the site I'm using this on is currently in development, but this would be a serious bug for a live site.

**Comment by dweerd** [comment] 2023-08-16 09:46
Yep, for my live site I currently switched to a plain text-input as a work-around.

**Comment by ifox** [comment] 2024-02-09 14:18
Hi everyone, I'm not able to reproduce this anymore on Twill 3.1.0, but someone else unfortunately reported it again in #2429. Are you all on Chrome on Windows like @iedex? Is it fixed for you in 3.1.0? I'll try to reproduce on Windows.

**Comment by iedex** [comment] 2024-02-11 11:39
Ah, sorry, It looks like I'm using the old assets, and I don't know why... 
![image](https://github.com/area17/twill/assets/657403/38216c2b-8628-4d24-a593-9af3b3810354)
Any hints? Thanks.

**Comment by iedex** [comment] 2024-02-11 11:51
Removed twill assets folder, did artisan twill:update, artisan cache:clear and how it loads latest assets.
The issue with date picker is fixed. Sorry for this false alarm.
Thank you!

**Closed** 2024-02-11 12:03 UTC
Labels: type: bug, impact: high

**Comment by BezBIS** [comment] 2024-02-13 10:11
@ifox I've tested on Chrome and Firefox for both Windows and Linux previously. On a Windows machine right now, but twill 3.1.0 seems to have fxed it.
