### ISSUE TITLE
Multiselect with dynamic values - ignores data from pivot table while reading

### ISSUE THREAD

**Issue by ResetButton** [area17/twill#666] opened 2020-06-01 15:46 UTC
I'm trying to implemet "Multiselect with dynamic values"
It seems all working fine. except reading data from pivot table, when building form.
Checking the fields and saving item - works, I see data in pivot table http://prntscr.com/srpmk8
But I when I render form (or just refreshing page) - all fields is unchecked.

I've a project on older Twill version and here all working fine

What I can miss ? And can you plz check this on actual version?

**Comment by ifox** [comment] 2022-02-06 13:05
Hi @ResetButton, sorry we have not been responding on this for so long. If you're still dealing with this issue, feel free to ping me, but since this hasn't been reported or confirmed since then, I'm going to close this issue.

**Closed by ifox** 2022-02-06 13:05 UTC

**Comment by shabaz-ejaz** [comment] 2024-06-25 10:56
I'm also having this issue, @ifox shame that you'd ignore the original issue for 2 years and then just close it at the first chance you get.

**Comment by ifox** [comment] 2024-06-25 11:08
I'm not sure why you feel the need to say it's a shame. This issue was created 4 years ago and had no further activity. If you are facing this issue, you are free to comment here, create a new issue, open a discussion, or even join our Discord to discuss it. Blaming me for closing it is not going to get you the support you're looking for. Please provide a reproduction.

**Comment by shabaz-ejaz** [comment] 2024-06-25 11:27
It had no further activity because **you** didn't respond :/  Then you closed the issue because it had no "further activity", what kind of weird logic is that?

The issue was created 4 years ago, you didn't respond for 2 years. Does that mean you should assume that it is no longer an issue? Don't you see the irony here?

**Comment by ifox** [comment] 2024-06-25 11:58
What's your point? Are you trying to give me feedback? There are more appropriate ways to do that. 

Thank you for opening a new issue. You could have simply referenced the closed issue with a comment saying you believe it hasn't been addressed. Blaming maintainers for closing an issue when hundreds of issues have been addressed and hundreds of community contributions have been merged for many years with a positive tone is just not necessary.

**Comment by shabaz-ejaz** [comment] 2024-06-25 12:20
I simply pointed out how it is a shame that an issue was closed out without the OP even getting any response for 2 years and the reason for closing it was inactivity. 

It's not the OP's fault that none of you guys followed up with anything. The OP did his part by posting the issue, from then onwards if you had any follow up questions or needed more information then that's on you. I find it a bit ridiculous that you'd close the issue based on the following:

> since this hasn't been reported or confirmed since then, I'm going to close this issue

But it is reported already? this exact issue is the report. Are you saying you need multiple reports of the same issue for you to take a look at it any further?
