### ISSUE TITLE
twill:install Cannot declare class CreateActivityLogTable

### ISSUE THREAD

**Issue by adnankussair** [area17/twill#183] opened 2019-02-12 03:26 UTC
Fresh Install of Laravel 5.7, Running MySQL 5.7, NPM v6.16, Composer Updated. I try to run php artisan twill:install but I keep on getting the following error:

PHP Fatal error:  Cannot declare class CreateActivityLogTable, because the name is already in use...
Symfony\Component\Debug\Exception\FatalErrorException  : Cannot declare class CreateActivityLogTable, because the name is already in use...

Attempted to delete all migration files and dump all mysql tables then rerun command but still no go.

I tried to reference some of the existing and closed issues about initial setup but couldn't find a solution for my issue. Any help would be greatly appreciated. Thanks! :)

<img width="1228" alt="screen shot 2019-02-11 at 7 02 13 pm" src="https://user-images.githubusercontent.com/239259/52609835-7d2fb880-2e33-11e9-96bc-d66cb255961b.png">

**Comment by luislavena** [comment] 2019-02-12 09:45
Hello @adnankussair, thank you for your report.

I found a similar situation and seems to be related to the migration files being duplicated, causing the same classes to be defined twice.

I can see from your screenshot that `create_activity_log_table.php` migration has been duplicated between `2019_02_12_024734` and `2019_02_12_021624`

This might be caused by an incomplete run of `twill:install` and at this time requires some manual cleanup.

Can you remove the older version of the generated migrations from the `database/migrations` folder? You can see all the files having the same timestamp mentioned above.

Let me know if that helps.

Cheers.

**Comment by adnankussair** [comment] 2019-02-12 14:58
Bah! Thanks. For some reason I tried removing all migrations and reinstalling yesterday evening and it didn't work. Magically it worked this morning. I'm sure I forgot to delete one of the migrations files which probably caused the errors. I did make sure to also drop all the generated tables and ran it all over again. Along the way I accidentally skipped the create admin user step so I simply dropped all mysql tables, removed all `database/migrations` files and this time made it through successfully. Thanks for your help and quick response!

**Comment by clexi** [comment] 2019-02-21 18:56
I have the same error. _create_activity_log_table is 10 times in migrations folder. Others too

**Comment by ptcampbell** [comment] 2019-05-07 04:51
+1

**Comment by luislavena** [comment] 2019-05-29 13:34
@clexi @ptcampbell I feel your pain and the team is working on adding a fix to this for the next release, so no double migrations are generated and to ease the upgrade path.

Will reopen this so the team can notify you once the fix has been deployed.

Cheers.

**Comment by Leonardo-Max** [comment] 2019-07-01 19:10
+ 1

**Comment by Sam-Black-0013** [comment] 2019-07-15 10:35
I am having the same problem. I dropped all tables and migrations but i get this error:

> Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `activity_log` add index `activity_log_log_name_index`(`log_name`))

**Comment by ifox** [comment] 2019-08-21 17:49
This has been fixed in 1.2.2 in c9bf1ff0adde85868968085f1b96921af529c024!

**Closed by ifox** 2019-08-21 17:49 UTC
Labels: question
