### ISSUE TITLE
Rendering Repeater fields. Child view required even when renderBlocks(false)

### ISSUE THREAD

**Issue by Riaan-ZA** [area17/twill#244] opened 2019-04-17 12:02 UTC
I'm rendering a repeater field called "quotes" with renderBlocks(false). I have the following block settings:

```
'blocks' => [
	'quotes' => [
		'title' => 'Quotes',
		'icon' => 'text',
		'component' => 'a17-block-quotes',
	],
],
'repeaters' => [
	'quote' => [
		'title' => 'Quote',
		'trigger' => 'Add quote',
		'component' => 'a17-block-quote',
		'max' => 10,
	]
]
```
However it still requires me to have a `quote.blade.php`  view file in the blocks folder, even though I'm not using it and rendering the children within the parent template `quotes.blade.php` is there anyway to prevent this?

**Comment by ifox** [comment] 2019-04-20 22:40
Hi @Riaan-ZA!

Not at the moment, you can leave it empty, but that would definitely be a great improvement as this is really not needed when rendering childs in the parent block view.

**Comment by yanhao-li** [comment] 2019-09-25 16:07
Hi @Riaan-ZA ,

Did you encounter such error while trying to preview the page, in that case, you may need to set `'block_preview_render_childs'  => false` in `config/twill.php`.  source code: https://github.com/area17/twill/blob/1.2/src/Http/Controllers/Admin/BlocksController.php#L66

Otherwise, I'm unable to reproduce the error on FE, could you please clarify it?
Thank you!

**Comment by ifox** [comment] 2020-03-04 02:17
I'm not able to reproduce this anymore either. Closing, but feel free to reach out again if that's still an issue.

**Closed by ifox** 2020-03-04 02:17 UTC
Labels: type: enhancement
