### ISSUE TITLE
DatePicker not setting the field value

### ISSUE THREAD

**Issue by iedex** [area17/twill#2429] opened 2024-02-08 11:16 UTC
## Description

Explained behavior below

### Steps to reproduce

Case 1:
- field has a value, eg. day 1
- click on field, calendar opens
- click on another day, eg. 5 -> calendar closes, displayed field date is 5
- save module's item -> saved value is 1, not 5 (also in request payload when save)

Case 2:
- field has a value, eg. day 1
- click on field, calendar opens
- click on another day, eg. 5 -> calendar closes, displayed field date is 5
- click on field, calendar opens
- click on another day, eg. 10 -> calendar closes, displayed field date is still 5
- save module's item -> saved value is 5

### Versions

Twill 3.1.0

**Comment by ifox** [comment] 2024-02-08 11:35
Did you update your Twill assets? This should be fixed with the build in 3.1.0

**Comment by iedex** [comment] 2024-02-08 11:53
I did this:
![image](https://github.com/area17/twill/assets/657403/dd4aa4f4-6c78-4471-bd1d-c3f47ae4f2d8)

Checked from an incognito window, and same issues.

**Comment by ifox** [comment] 2024-02-08 11:57
Ok, sorry to hear that, it's been an annoying bug and I thought my fix was enough. At least I wasn't able to reproduce it anymore on my end. I'll try again.

**Comment by ifox** [comment] 2024-02-08 14:18
I still can't reproduce. Which browser are you using?

**Comment by iedex** [comment] 2024-02-08 18:33
Chrome on Windows

**Comment by iedex** [comment] 2024-02-08 18:41
![image](https://github.com/area17/twill/assets/657403/c431f186-0dc9-440d-83c6-6e31473e59aa)

**Comment by ifox** [comment] 2024-02-08 19:56
You have duplicate js files that you can delete. You can try deleting `public/assets/twill` and running `twill:update` again, but I highly doubt that it will help since your manifest should be correct and use the latest ones you got, which do match the one I use in my testing.

I wanted to confirm something else: in which context are you using the faulty date picker field? Form? Block? Publisher sidebar?

**Comment by iedex** [comment] 2024-02-08 20:12
Form, Twill / ...Controller / getForm...
```
DatePicker::make()->name('first_reg')->label('1st reg.')->time24Hr()->withoutTime()->allowClear(),

**Comment by iedex** [comment] 2024-02-08 20:22
now I realized the absurd "->time24Hr()->withoutTime()". anyway, I don't think this is the problem.

**Comment by ifox** [comment] 2024-02-09 14:18
Closing as a dupe of #2237

**Closed as not planned by ifox** 2024-02-09 14:18 UTC
