### ISSUE TITLE
Images upload - folders

### ISSUE THREAD

**Issue by awgul** [area17/twill#96] opened 2018-12-01 08:42 UTC
Hey,

I use endpoint_type: local.

When I upload for example 10 images at once some get into folder like `f979ba56-e280-40cd-8827-71818938f8b8` and some go straight to `uploads/` folder.
Why is it so random?

Can we switch off the folder creation at all if it isn't working properly?

**Comment by ifox** [comment] 2018-12-04 00:51
Hi @awgul!

This shouldn't be random at all. Every batch of uploads, wether it's a single file or multiple, should end up in a single generated folder under uploads.

Can you share a repo to reproduce this?

**Comment by ifox** [comment] 2019-03-16 19:45
Hey @awgul I really can't reproduce so I'm going to close the issue but feel free to post again and I can reopen if you are still seeing this.

**Closed by ifox** 2019-03-16 19:45 UTC
Labels: bug

**Comment by valentinrabitz** [comment] 2019-08-04 20:53
Hi @ifox, @awgul,

I am experiencing the same issue. When selecting multiple images and uploading them, the first 5 images are stored in the folder, the others go straight to the root of the uploads folder. 

After unsuccessfully modifying some PHP settings, I was able to temporarily solve this issue by increasing the `maxConnections` size in `Uploader.vue`. 

Somehow every upload request after the 5th one was missing the `unique_folder_name` parameter, but instead had a `width` and `height` parameter in the form data (viewable in the browser's dev tools).

**Comment by arkid** [comment] 2019-09-11 17:58
@ifox can you consider opening as I have just discovered I have the same symptoms.  Going to try editing the view file as well as a fix.
