### ISSUE TITLE
Published state does not reset after creating an item using the modal

### ISSUE THREAD

**Issue by mazeeblanke** [area17/twill#733] opened 2020-08-30 19:09 UTC
There is a bug in the create modal form

Steps to reproduce bug:

1. Go to module listing
2. Click Add new
3. Fill the form and set the published state to live (i.e published)
4. Click 'Create and add another'
5. Repeat steps 1 to 4, but this time the published state will be set to draft but behind the scenes it's still set as 'live',
6. Then click 'create' or 'Create and add another' but instead of the published state to be set to 'draft', it will be set to 'live'

**Comment by ptrckvzn** [comment] 2021-04-28 21:29
Hi @mazeeblanke ! I am trying these steps in Twill 2.x and I can't reproduce the bug. The modal seems to always respect the draft/live setting from the modal. Which version were you using? Thanks

**Comment by ifox** [comment] 2021-04-28 23:06
Fixed in #732, thanks guys!

**Closed by ifox** 2021-04-28 23:06 UTC
