### ISSUE TITLE
Error in the installation of Twill

### ISSUE THREAD

**Issue by CarlosQS** [area17/twill#1380] opened 2022-01-16 00:19 UTC
## Description

Hi, I have tried to install Twill but I have a problem despite having all the correct requirements and with their correct versions.

### Expected result

Output console:
  [InvalidArgumentException]
  Package area17/twill at version 2.0 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version.

![image](https://user-images.githubusercontent.com/56250493/149642302-ce5e3aa5-3b8a-4587-89ac-f831c6b3ceb7.png)

### Versions

Twill version: 2.0
Laravel version: 8.79.0
PHP version: 8.0.10
Database engine: MySQL

**Comment by haringsrob** [comment] 2022-01-16 11:44
Hey @CarlosQS , can you try:

`composer require area17/twill:"^2.6"`?

**Comment by tanzibhossain** [comment] 2022-01-19 07:45
> Hey @CarlosQS , can you try:
> 
> `composer require area17/twill:"^2.6"`?

Thanks, It worked for me.

**Comment by haringsrob** [comment] 2022-01-19 08:05
@ifox so I have been testing this because I have seen this reported before. 

But I am unable to reproduce. Does composer maybe try to find a version within the current lockfile constraints first before it tries to take the latest version?

Should we update the documentation to install the latest version?

**Comment by tanzibhossain** [comment] 2022-01-19 08:11
I have encountered this with xampp on windows. Do you need any info to reproduce it ?

**Comment by haringsrob** [comment] 2022-01-19 08:12
@tanzibhossain thanks, did you already have a composer.lock file/working project when you wanted to install twill or was it a fresh Laravel installation?

**Comment by tanzibhossain** [comment] 2022-01-19 08:25
@haringsrob you're welcome. It was fresh laravel install. 
I'm also attaching the error screenshot, it might help.

![image](https://user-images.githubusercontent.com/58650939/150092089-e91ea99b-1a04-475e-901e-42d5d3799dbc.png)

**Comment by haringsrob** [comment] 2022-01-28 08:08
Hey @tanzibhossain, I have tried to reproduce this using various configs but I was unable to.

I do not have a windows machine to try this with currently. But also that seems like a big edge case.

Since your issue was resolved by requiring the latest version specifically I will close this until we get another similar report.

Thank you for your time and collaboration!

**Closed by haringsrob** 2022-01-28 08:08 UTC
