### ISSUE TITLE
WYSIWYG Editor not saving

### ISSUE THREAD

**Issue by twan-2022** [area17/twill#1949] opened 2022-11-24 10:21 UTC
## Description

I created a page module specifically for landingspages but sometimes when I save the content which is a WYSIWYG editor, it just posts the old content instead of the updated one and nothing gets updated. 

### Steps to reproduce

I open a page and edit the content like this:

![d6fc3d3ebc4dadb1c4ab582dcd9fa9e5](https://user-images.githubusercontent.com/11909652/203758993-0f6f7fd6-607c-4b8e-850a-3b1ecb879bd5.png)

### Expected result

The added text should be posted to be saved in the database but when I check the page nothing is changed. So I checked the network tab and see what actually is posted. And it shows this:

### Actual result

![c3c13e02377bd18bb64d6e0e07f19e79](https://user-images.githubusercontent.com/11909652/203759219-a776e9a2-f7fe-41dd-ad31-b6bd3d5dc31d.png)

If you look at the 'description' it is not posting the newly added text.

So the old content just gets posted. Why is that happening?

### Versions

Twill version 2.0
Laravel version 8.75
PHP 8.0
Database: mysql PHPmyadmin

**Comment by haringsrob** [comment] 2022-11-25 08:32
Hey @twan-2022 as @kallefrombosnia mentioned, please try to do an upgrade first to see if that solves the issue.

Kind regards,

**Comment by twan-2022** [comment] 2022-11-27 13:24
I updated to the latest version (2.11.0) and I still got the same issue.

**Comment by adam-jones-net** [comment] 2023-01-11 12:02
> I updated to the latest version (2.11.0) and I still got the same issue.

Any fix for this @twan-2022  - I get the same issue.   I'm on 2.12.3.    It doesn't seem to happen on my local WIMP stack, only my live LAMP server.

**Comment by ifox** [comment] 2023-01-11 12:24
Hi @adam-jones-net do you see an error in console mentioning `mutations`? The issue is that before the bug was fixed, the WYSIWYG field was saving specific html it isn't able to boot from anymore. So you might need to cleanup your database to remove that. cc @haringsrob

**Comment by ifox** [comment] 2023-01-31 13:22
Closing as support was provided in https://github.com/area17/twill/issues/458.

**Closed by ifox** 2023-01-31 13:22 UTC
Labels: status: on hold
