### ISSUE TITLE
Image field brings error if not first in the list

### ISSUE THREAD

**Issue by ammma** [area17/twill#1056] opened 2021-07-15 12:45 UTC
Steps to reproduce:
- add media config to model: 
`    public $mediasParams = [
        'cover' => [
            'default' => [
                [
                    'name' => 'default',
                    'ratio' => 1,
                ],
            ],
        ],
    ];`
- add media column to `$indexColumns` in controller as any element but not first:
`    protected $indexColumns = [
        ....,
        'image' => [
            'thumb' => true,
            'field' => 'cover',
            'variant' => [
                'role' => 'cover',
                'crop' => 'default'
            ]
        ],
        ....,`

List view will produce an error:
`ErrorException
Undefined index: title`
`vendor\area17\twill\src\Http\Controllers\Admin\ModuleController.php:1154`

**Comment by pboi20** [comment] 2021-07-15 14:34
Duplicate of https://github.com/area17/twill/issues/552

**Closed** 2021-11-04 20:56 UTC
