### ISSUE TITLE
noTranslate for file fields

### ISSUE THREAD

**Issue by tchapi** [area17/twill#473] opened 2019-11-26 10:26 UTC
The "noTranslate => true" flag for file fields does not work. In fact, it is not implemented, as far as I know in `_files.blade.php` (see https://github.com/area17/twill/blob/master/views/partials/form/_files.blade.php)

Is it possible to achieve this functionnality anyway (a non translated file field) ?

Thanks

**Comment by tchapi** [comment] 2019-11-26 10:33
(It's mentionned in the docs here : https://github.com/area17/twill/blob/master/docs/.sections/crud-modules.md)

**Comment by Archy812** [comment] 2020-12-07 17:12
Problem still persist

**Comment by ifox** [comment] 2023-01-31 13:15
Closing as a dupe of #1712

**Closed by ifox** 2023-01-31 13:15 UTC
Labels: type: bug, impact: low
