### ISSUE TITLE
missing in documents

### ISSUE THREAD

**Issue by DJafari** [area17/twill#4] opened 2018-07-08 14:33 UTC
i think in installation document something is missing
does need update `packages.json` dependecies ?

because when i run `npm run cms-build` throws to error

```
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:291:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:167     ░⸩ ⠙ extractTree: sill extractTree next-tick@1.0.0 -> /Users/davood/Desktop/twill/vendor/area17/twill/node_modules/next-tick
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:291:5)
    at PassThrough.Writable.end (_stream_writable.js:579:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/libcipm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:252:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:165:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:301:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:102:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:291:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davood/.npm/_logs/2018-07-08T14_20_16_618Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ cms-build: `npm run cms-copy-blocks && cd vendor/area17/twill && npm ci && npm run prod && cp -R public/ ${INIT_CWD}/public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ cms-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davood/.npm/_logs/2018-07-08T14_20_16_698Z-debug.log
```

**Comment by ifox** [comment] 2018-07-09 16:05
Hi Davood! Thanks for reporting your issue. Which version of NPM are you running?

As noted in #2, we're going to update our documentation with a more detailed requirements section this week.

The `npm run cms-build` command is actually running `npm ci` for you behind the scene to install the dependencies used by Twill's frontend.

The `npm ci` command is a relatively new one ([available since NPM 5.7.0](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable)) that replace the `npm install` command to bypasses a package’s package.json to install modules from a package’s lockfile. This ensures reproducible builds.

**Comment by DJafari** [comment] 2018-07-10 15:05
@ifox thanks for your answer

```
➜  twill npm doctor
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v6.1.0
node -v                             v10.5.0
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 5816 tarballs
```

**Comment by ifox** [comment] 2018-07-10 21:56
Interesting. I'm going to have to investigate this one as this is the first time I see your error with a recent version of Node/NPM.

Can you try to run the following in your project and let me know if you're still getting the same error:

```sh
rm -rf vendor/area17/twill/node_modules
rm -rf vendor/area17/twill/public
npm run cms-build
```

Thanks @DJafari!

**Comment by DJafari** [comment] 2018-07-10 22:20
sorry, i create new project with laravel and install twill, it will ok now, but how ? i dont know :))

**Comment by ifox** [comment] 2018-07-10 22:35
Cool @DJafari. Oh well, NPM, you never know what to expect! Thankfully we have the `ci` command now, that's better than what it used to be.

Closing this one, feel free to open a new one once you hit another blocker!

**Closed by ifox** 2018-07-10 22:35 UTC

**Comment by osmanzeki** [comment] 2018-07-13 21:56
I can confirm that I had this problem when I was running an older version of NPM:

```
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.3.0                       Use npm v6.1.0
node -v                             v8.5.0                       Use node v8.11.3
npm config get registry             https://registry.npmjs.org/
which git                           /usr/local/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 4950 tarballs
```

Now with NPM 6.1.0, this no longer seems to happen. The `npm ci` command did not exist in my version of NPM.
