### ISSUE TITLE
Bug: Non Translatable Medias are not displayed on reload, but saved in the database.

### ISSUE THREAD

**Issue by Keimeno** [area17/twill#814] opened 2021-04-01 14:08 UTC
I have the following setup: My Twill instance supports both German (`de`) and English (`en`), with German being the default language.

When I create the following non-translatable media field:
```php
@formField('medias', [
  'name' => 'myImage',
  'label' => 'My Image',
  'required' => true,
  'translated' => false,
])
```
I am able to add an image and save it. It will also be saved in the database, but under the locale `en`.

If I reload the page the image is not displayed any more. It seems that the `mediaKey` variable inside the `MediaField.vue` is prioritizing the locale `en`, instead of the default locale: `de`.

**Comment by Keimeno** [comment] 2021-04-01 14:16
I can take a closer look into the problem in the next couple of days and potentially open a PR regarding this issue.

**Comment by Keimeno** [comment] 2021-04-01 14:19
One potential fix would be to save the images under the current default language (in my case `de`). This would, however, cause a problem, when changing the default language.

A better fix would be to deprecate using a locale all together, or defining a placeholder locale, that doesn't/couldn't exist.

**Comment by daun** [comment] 2021-04-06 07:25
Duplicate of #483.

**Comment by ConstantMath** [comment] 2021-04-20 11:30
Same issue here.
I bypass it by using : ` 'translated' => false, ` in the `@formField`

**Comment by ConstantMath** [comment] 2021-04-20 11:36
Another bug related to the translated medias is that the Notes and FieldNotes don't appear when the media formField is set on `'translated' => true`.

**Comment by Keimeno** [comment] 2021-04-20 18:14
@ConstantMath the bypass sadly doesn't work if the model, it is being saved to, is non translatable by default.

**Comment by ptrckvzn** [comment] 2021-04-26 14:06
Thanks for reporting this bug. I will close it as it's a duplicate of #483.

**Closed by ptrckvzn** 2021-04-26 14:06 UTC
