### ISSUE TITLE
Laravel 5.7.*

### ISSUE THREAD

**Issue by Sceko** [area17/twill#493] opened 2019-12-30 18:47 UTC
after  composer require area17/twill:"1.2.*"

array_key_exists(): The first argument should be either a string or an integer

**Comment by yanhao-li** [comment] 2020-01-02 23:25
Hi @Sceko 
Could you provide a detailed log?
Thank you!

**Comment by Sceko** [comment] 2020-01-03 16:50
In ServiceProvider.php line 173:
                                                                                
  array_key_exists(): The first argument should be either a string or an integer
                                                                                

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by yanhao-li** [comment] 2020-01-03 17:43
Hi @Sceko 

Unfortunately, I can't reproduce the issue on my laptop with the same scripts you posted above. 

However, looks like you are trying to install Twill on a fresh Laravel app, could you try the [create-twill-app](https://github.com/yanhao-li/create-twill-app)?

**Comment by Sceko** [comment] 2020-01-03 19:07
Installation failed, reverting ./composer.json to its original content.

**Comment by yanhao-li** [comment] 2020-01-03 19:45
Hey @Sceko 

I just added support for Symfony 5.* and released a new version for it.
Please try
`composer global require yanhaoli/create-twill-app:"1.0.5"`

Let me know the outcome, thanks!

**Comment by Sceko** [comment] 2020-01-03 23:54
this work but next error for upload
 { "type": "ErrorException", "message": "join(): Passing glue string after array is deprecated. Swap the parameters", "file":

**Comment by yanhao-li** [comment] 2020-01-04 02:05
Looks like this issue has been fixed here: https://github.com/area17/twill/commit/57fbdaf1b52d0a923bd84420ddd981e5f4a36007#diff-9dde1496a7fda7b26f4835947d387e48

**Comment by Sceko** [comment] 2020-01-04 09:55
And new error :)
{ "type": "ErrorException", "message": "join(): Passing glue string after array is deprecated. Swap the parameters", "file": "C:\\xampp\\htdocs\\sceko\\vendor\\area17\\twill\\src\\Services\\MediaLibrary\\Glide.php", "line": 58 }

**Comment by yanhao-li** [comment] 2020-01-04 13:46
@Sceko 
Yes, you could use `dev-master` for now, I will update the `create-twill-app` package as well later. 
Thank you for your patience!
Closing this ticket, please reopen if you have further questions.

**Closed by yanhao-li** 2020-01-04 13:46 UTC
Labels: status: on hold

**Comment by buivietha0409** [comment] 2020-12-15 14:46
In ServiceProvider.php line 173:

array_key_exists(): The first argument should be either a string or an integer 
Error why can anyone help me.

**Comment by venkataadithan** [comment] 2020-12-15 15:00
@buivietha0409 could you please specify the twill version you are trying to install?

**Comment by venkataadithan** [comment] 2020-12-15 15:01
> In ServiceProvider.php line 173:
> 
> array_key_exists(): The first argument should be either a string or an integer
> Error why can anyone help me.

could you please specify the twill version you are trying to install?

**Comment by buivietha0409** [comment] 2020-12-15 15:07
In ServiceProvider.php line 173:

  array_key_exists(): The first argument should be either a string or an
integer

*CÔNG TY CỔ PHẦN SMART LAND*
Add:N06B1,Thành Thái,Hà Nội
Tel:
0979.536.000
0944.17.0000

websize:http://duandothihanoi.com.vn/








Vào Th 3, 15 thg 12, 2020 vào lúc 22:01 Venkat Aadithan <
notifications@github.com> đã viết:

**Comment by buivietha0409** [comment] 2020-12-15 15:11
> > In ServiceProvider.php line 173:
> > array_key_exists(): The first argument should be either a string or an integer
> > Error why can anyone help me.
> 
> could you please specify the twill version you are trying to install?


I install purely models and controllers .laravel always reports the same error

**Comment by venkataadithan** [comment] 2020-12-15 15:16
> > > In ServiceProvider.php line 173:
> > > array_key_exists(): The first argument should be either a string or an integer
> > > Error why can anyone help me.
> > 
> > 
> > could you please specify the twill version you are trying to install?
> 
> I install purely models and controllers .laravel always reports the same error

Please check the php version you have is compatible with the laravel version you are working on.

**Comment by buivietha0409** [comment] 2020-12-15 15:26
> > > > Trong ServiceProvider.php dòng 173: 
> > > > array_key_exists (): Đối số đầu tiên phải là chuỗi hoặc số nguyên. 
> > > > Lỗi tại sao mọi người có thể giúp tôi.
> > > 
> > > 
> > > bạn có thể vui lòng chỉ định phiên bản twill bạn đang cố gắng cài đặt không?
> > 
> > 
> > Tôi cài đặt hoàn toàn các mô hình và bộ điều khiển .laravel luôn báo cùng một lỗi
> 
> Vui lòng kiểm tra phiên bản php bạn có có tương thích với phiên bản laravel bạn đang làm việc không.

I am using:
 "php": "^7.1.3",
  "laravel/framework": "5.7.*",
